<a href="https://colab.research.google.com/github/mradzikowska/mbcs-internship/blob/main/super_simple_RSA_trial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#Create random data
data1= np.random.normal(size = 5)
data2 = np.random.normal(size = 5)
data3 = np.random.normal(size = 5)
#Make a data frame
import pandas as pd
data_1 = pd.DataFrame ({"a": data1 ,
                      "b": data2 ,
                      "c": data3 })
data_1 = data_1.T
print(data_1)


          0         1         2         3         4
a  0.392543 -0.911443  0.772151 -0.090814 -1.135782
b  1.479959 -0.381182 -0.979437  1.447932 -1.726879
c  0.186623  1.185414  0.618395 -0.017583  0.927143


In [ ]:
from scipy.spatial.distance import euclidean, pdist, squareform

#compute similarity matrix between each of the rows -- how are columns treated? As one vector? 
from sklearn.metrics import pairwise_distances #for distance matrix
from scipy.spatial.distance import cosine #for cosine similarity

dist_matrix_1 = 1-pairwise_distances(data_1, metric="cosine")
distance_matrix_1 = pd.DataFrame (dist_matrix_1)
print(distance_matrix_1, "RDM 1")


          0         1         2
0  1.000000  0.407719 -0.568938
1  0.407719  1.000000 -0.508067
2 -0.568938 -0.508067  1.000000 RDM 1


In [ ]:
#Create second set of data 
data_a = np.random.randint (low=1,high =20,size =3)
data_b = np.random.randint (low = 1, high = 20, size =3)
data_c = np.random.randint (low = 1, high = 20, size =3)

data_2 = pd.DataFrame ({"a": data_a,"b" : data_b,"c" : data_c})
data_2 = data_2.T
print(data_2)


    0   1   2
a   4   9  14
b   8  16   7
c  18  16  19


In [ ]:
#Compute a second smilarity matrix
from sklearn.metrics import pairwise_distances #for distance matrix
from scipy.spatial.distance import cosine #for cosine similarity

dist_matrix_2 = 1-pairwise_distances(data_2, metric="cosine")
distance_matrix_2 = pd.DataFrame (dist_matrix_2)
print(distance_matrix_2, "RDM 2")

          0         1         2
0  1.000000  0.833304  0.917949
1  0.833304  1.000000  0.904522
2  0.917949  0.904522  1.000000 RDM 2


In [ ]:
#normalize matrix?? #I shoudl keep all in list of lists and then do a for loop?
#change it to numpyy
np_distance_matrix_1 = distance_matrix_1.to_numpy ()
np_distance_matrix_2 = distance_matrix_2.to_numpy()
RDM1_norm = np.linalg.norm (np_distance_matrix_1, axis = 0) #thats row wise but I'm not sure baout it, also the data is already form norla distribution and between 0 and 1 so why is it necessary?
RDM2_norm = np.linalg.norm (np_distance_matrix_2, axis = 0)
print(RDM1_norm, RDM2_norm)

[1.22062499 1.19346856 1.25770547] [1.59280436 1.58510449 1.63119287]


In [ ]:
#Compare Matrices WRONGGGG
RSA= np.dot (np_distance_matrix_1, np_distance_matrix_2)
print(RSA)



[[ 0.81749791  0.72640602  0.71780143]
 [ 0.77464339  0.88019574  0.77071991]
 [-0.07436409 -0.07764373  0.01818578]]
4.4961156069303


Samira's code

In [ ]:

def compute_dist_of_dists(x, C, labels):
  keys = np.asarray(list(x.keys()))
  klz = np.zeros((len(keys), len(keys)))
  prz = np.zeros((len(keys), len(keys)))
  mean_p_value = np.zeros((len(keys), len(keys)))
  for i in np.arange(len(keys)):
    for j in np.arange(len(keys)):
      klz[i][j] = np.sum(sp.stats.entropy(C[keys[i]], C[keys[j]], base=None))
      pz = []
      p_values = []
      for a,b in zip(C[keys[i]], C[keys[j]]):
        p, p_value = sp.stats.pearsonr(a,b)
        pz.append(p)
        p_values.append(p_value)

      prz[i][j] = np.mean(pz)
      mean_p_value[i][j] = np.mean(p_values)

  return klz, prz, labels, mean_p_value

def compute_dist_of_dists_over_time(x, C, labels):
  """
  :param x:
  :param C: pair wise distances of xs
  :param labels: e.g. tokens of the story
  :return:
  """
  keys = np.asarray(list(x.keys()))
  klz = np.zeros((len(keys), len(labels)))
  prz = np.zeros((len(keys), len(labels)))
  for i in np.arange(len(keys)):
    for j in np.arange(len(keys)):

      klz[i][j] = np.sum(sp.stats.entropy(C[keys[i]], C[keys[j]], base=None))
      pz = []
      for a,b in zip(C[keys[i]], C[keys[j]]):
        p, _ = sp.stats.pearsonr(a,b)
        pz.append(p)

      prz[i][j] = np.mean(pz)

  return klz, prz, labels

if __name__ == '__main__':
    print(pad_lists([['a','b'],['c']], ''))
    print(concat_lists([['a', 'b'], ['c']]))